// Operational store allocations reconciled against the live onboarding sheet.
// `originalOnboarder` preserves acquisition credit; `assignedAgent` controls
// current portfolio access and does not transfer ownership.
const allocation = (assignedAgent, currentSupervisor, stores) => Object.freeze(
  stores.map((store) => Object.freeze({ ...store, assignedAgent, currentSupervisor }))
);
const ownedStores = (originalOnboarder, rows) => rows.map(([id, name, address, territory]) => ({ id, name, address, territory, originalOnboarder }));

export const STORE_ALLOCATIONS = Object.freeze({
  Towobola: allocation('Towobola', 'Towobola', [
    { id: 'store-euro-gadget-commerce-ventures', name: 'Euro gadget commerce ventures', address: '6 Olayeni computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-slick', name: 'Slick', address: '2 pepple street, Msquare plaza, computer village.', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-plug-of-life', name: 'Plug🔌 of life', address: '13, Oshitelu Street, computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-k-c-eze-gadgets', name: 'K.C Eze Gadgets', address: '10, pepple street, Goodness plaza. Computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-river-of-gold-communications', name: 'River of Gold Communications', address: '15, Ola-Ayeni street, computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-akybenny-hub-concept', name: 'Akybenny Hub Concept', address: '4A, Binite Plaza, Shop E6/7, Computer Village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-buyme', name: 'Buyme', address: '7, Kodesoh Street, Computer Village, Ikeja, Lagos.', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-darling-ronnys-phones', name: 'Darling Ronny’s Phones', address: '10 Otigba street opposite police post computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-alpharicon-global', name: 'Alpharicon Global', address: '16 obafemi Awolowo way computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-mayour-lee-it-hub', name: 'Mayour Lee IT HUB', address: '13 Oshitelu Street, computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-river-of-gold', name: 'River of Gold', address: '10, pepple street, Goodness plaza. Computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-royaline-technologies', name: 'Royaline Technologies', address: '2 Simbiat Abiola way opposite ikeja', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-judest', name: 'Judest', address: '17, Olayeni street, Ikeja', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-links-mobiles', name: 'links mobiles', address: '10, ola ayeni street computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-tohflex-gadgets', name: 'tohflex gadgets', address: '40,obafemi awolowo way', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-maximilliandream', name: 'maximilliandream', address: '15, olayeni street,glory plaza,computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-zeezco-ventures', name: 'Zeezco Ventures', address: '19 Mokolu street ogba', territory: 'OGBA', originalOnboarder: 'Towobola' },
    { id: 'store-fsa-gadgets', name: 'FSA GADGETS', address: '17, Alafia Avenue Street, Ejigbo, Lagos', territory: 'Oshodi/isolo', originalOnboarder: 'Towobola' },
    { id: 'store-jaydee-exclusive', name: 'Jaydee Exclusive', address: '5, Rotimi Square off Benson Busstop, surulere', territory: 'Surulere/Lawanson', originalOnboarder: 'Towobola' },
    { id: 'store-tobest-footies', name: 'Tobest Footies', address: '19, Adegbola street off Cole street, lawanson, Surulere', territory: 'Surulere/Lawanson', originalOnboarder: 'Towobola' },
    { id: 'store-monicity-phones-and-logistics', name: 'Monicity phones and logistics', address: '13/15 Ijaiye road opposite Nigerian Institute of Journalism Ogba.', territory: 'OGBA', originalOnboarder: 'Towobola' },
    { id: 'store-precious-hair-beauty', name: 'Precious Hair Beauty', address: '15, Orile, Igomu, Lagos.', territory: 'Orile', originalOnboarder: 'Towobola' },
    { id: 'store-ytee-touch-hair-studio', name: 'Ytee Touch Hair Studio', address: '46, Akerele street, Surulere', territory: 'Surulere/Lawanson', originalOnboarder: 'Towobola' },
    { id: 'store-global-god-grace-communication', name: 'Global God Grace Communication', address: '8, mercy wing, Goshenland plaza, kosoko road, Berger.', territory: 'Berger', originalOnboarder: 'Towobola' },
    { id: 'store-clinton-enterprises', name: 'Clinton Enterprises', address: 'Maximum Correctional Barracks, Kirikiri, Apapa, Lagos.', territory: 'Apapa', originalOnboarder: 'Towobola' },
    { id: 'store-arice-chine-nig-ventures', name: 'Arice & Chine Nig. Ventures', address: '12 saka tinubu, Victoria Island', territory: 'Saka Tinubu', originalOnboarder: 'Towobola' },
    { id: 'store-d-real-phones-and-gadget-nig-ltd', name: 'D-Real Phones and Gadget Nig Ltd', address: '7 Saka Tinubu, Victoria Island', territory: 'Saka Tinubu', originalOnboarder: 'Towobola' },
    { id: 'store-bumax-ventures-resources-limited', name: 'Bumax Ventures Resources Limited', address: '9, tech plaza, Saka Tinubu, Victoria island.', territory: 'Saka Tinubu', originalOnboarder: 'Towobola' },
    { id: 'store-stevoo-gadgets', name: 'Stevoo Gadgets', address: 'Shop D 14m, 12 Saka Tinubu Street, Victoria Island.', territory: 'Saka Tinubu', originalOnboarder: 'Towobola' },
    { id: 'store-b-oclock-gadget-hub', name: 'B O’clock Gadget Hub', address: '8, Saka Tinubu Street, Victoria Island.', territory: 'Saka Tinubu', originalOnboarder: 'Towobola' },
    { id: 'store-meg-seafoods', name: 'Meg seafoods', address: '22, Isaac Okormor Street Off Gafari Balogun Street, Ogudu, Lagos.', territory: 'Ogudu', originalOnboarder: 'Towobola' },
    { id: 'store-primax-phone-logistics', name: 'Primax Phone & Logistics', address: '68, College Road, Ifako Ijaiye Ogba, Lagos.', territory: 'OGBA', originalOnboarder: 'Towobola' },
    { id: 'store-golden-tech-view-communications', name: 'Golden tech view communications', address: 'Exodus plaza, shop 127 ASPMDA Main gate', territory: 'Tradefair international market', originalOnboarder: 'Towobola' },
    { id: 'store-chidec-communication-ltd', name: 'Chidec Communication Ltd', address: 'Exodus plaza, Shop 87/88, ASPMDA Tradefair complex', territory: 'Tradefair international market', originalOnboarder: 'Towobola' },
    { id: 'store-chy-nats-communication-ent-nig', name: 'Chy-nats communication Ent Nig', address: 'Exodus plaza, Shop 119, ASPMDA Tradefair complex', territory: 'Tradefair international market', originalOnboarder: 'Towobola' },
    { id: 'store-chrislas-intl-ltd', name: 'Chrislas Int’l Ltd', address: 'Exodus plaza, Shop 96, ASPMDA Tradefair complex', territory: 'Tradefair international market', originalOnboarder: 'Towobola' },
    { id: 'store-nonstop-chibest-communication-enterprise', name: 'Nonstop Chibest Communication Enterprise', address: '16. Old Ojo Road, Maza Maza, Lagos.', territory: 'Maza Maza', originalOnboarder: 'Towobola' },
  ]),
  Queen: allocation('Queen', 'Towobola', [
    { id: 'store-amprex-hub-enterprises', name: 'Amprex Hub Enterprises', address: '12, Pepple Street, Computer village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-fb-communications', name: 'FB Communications', address: '11, Otigba Street, Computer Village', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-avix-mobile', name: 'Avix Mobile', address: '2 Medical road computer village opposite slot, Ikeja', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-vivo-exclusive-royalline', name: 'Vivo Exclusive Royalline', address: '2 Simbiat Abiola Way ikeja', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-primtech-phones', name: 'Primtech Phones', address: 'Suit 50 Store, 14B Divine Plaza, Pepple Street, Computer Village, Ikeja, Lagos.', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-almond-kan-global-investment-ltd', name: 'Almond Kan Global Investment Ltd', address: 'Suit 52 Store, 14B Divine Plaza, Pepple Street, Computer village, Ikeja, Lagos.', territory: 'Computer Village', originalOnboarder: 'Towobola' },
    { id: 'store-mchrist-store', name: 'mchrist store', address: '17, simbiat abiola way computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-morgan-mobile-and-technology', name: 'Morgan mobile and technology', address: '6,idowu lane', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-kamdi-computer', name: 'kamdi computer', address: '23, ikeja club plaza awolowo way', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-fm-reliable', name: 'FM reliable', address: '10, otigba street computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-aos-city-limited', name: 'Aos city limited', address: '14, ola ayeni opposite fidelity bank computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-always-mobile-phone', name: 'Always mobile phone', address: '12, ola ayeni street computer village', territory: 'Computer Village', originalOnboarder: 'Sarah' },
    { id: 'store-eddybass-venture', name: 'Eddybass Venture', address: '19 Ola-ayeni street', territory: 'Computer Village', originalOnboarder: 'Chile Nwaiwu' },
    { id: 'store-finet-awolowo', name: 'Finet Awolowo', address: '22b Awolowo way ikeja', territory: 'Computer Village', originalOnboarder: 'Chile Nwaiwu' },
  ]),
  'Chile Nwaiwu': allocation('Chile Nwaiwu', 'Chile Nwaiwu', ownedStores('Chile Nwaiwu', [
    ['store-3chub-lawanson', '3chub lawanson', 'No 12, itire road lawanson bus stop', 'Surulere/Lawanson'],
    ['store-adaugo-telecoms', 'Adaugo Telecoms', 'Asa ugo tech', 'Surulere/Lawanson'],
    ['store-great-favour', 'Great favour', '2 lawanson bus stop surulere lawanson', 'Surulere/Lawanson'],
    ['store-signal-home-delite', 'Signal home delite', '1,Sunday Igbodo estate besides kilimajaro Ago place way', 'Maryland/Cantoment/leventis'],
    ['store-micro-station-okota', 'Micro station okota', 'Lorddre101@gmail.com', 'Maryland/Cantoment/leventis'],
    ['store-energyreturn', 'Energyreturn', '116/118 Agor palace way', 'Maryland/Cantoment/leventis'],
    ['store-benedict-cee-communication', 'Benedict cee communication', '124 ijesha road Johnson bustop', 'Surulere/Lawanson'],
    ['store-olas-and-bs-nig-ltd', 'Olas and BS Nig ltd', '124, ijesha road Johnson bustop surulere', 'Surulere/Lawanson'],
    ['store-dozzy-digital', 'Dozzy digital', '1 , lawanson road surulere', 'Surulere/Lawanson'],
    ['store-zinne-communication', 'Zinne communication', '1 Lawanson road surulere', 'Surulere/Lawanson'],
    ['store-jovylink-concept', 'Jovylink concept', 'Shop 0 6 lawanson complex Gtb plaza up step by olatilewa lawanson', 'Surulere/Lawanson'],
    ['store-kolia-angel-phone-and-gadgets', 'Kolia angel phone and gadgets', 'D1 lawanson D yard', 'Surulere/Lawanson'],
    // Shared with Queen; the same store IDs preserve one physical-store identity.
    ['store-eddybass-venture', 'Eddybass Venture', '19 Ola-ayeni street', 'Computer Village'],
    ['store-finet-awolowo', 'Finet Awolowo', '22b Awolowo way ikeja', 'Computer Village'],
    ['store-mercy-dibio', 'Mercy dibio', 'No23,ikeja club plaza computer village', 'Computer Village'],
    ['store-zublex-phone-and-assesory', 'Zublex phone and assesory', 'Agege pecilna', 'Abule Egba'],
    ['store-dozie-tech', 'Dozie tech', '23, Awolowo way ikeja club plaza', 'Ikeja Along'],
    ['store-foundation-mobile', 'Foundation mobile', '28,Adreiogunsaya', 'Surulere/Lawanson'],
    ['store-sudha-nig-adenirn-ogunsanya', 'Sudha nig Adenirn Ogunsanya', '47, Adenirn Ogunsanya street surulere', 'Surulere/Lawanson'],
    ['store-3chub-adriana-ogunsanya', '3chub Adriana Ogunsanya', '63 3chub Adenirn Ogunsanya street', 'Surulere/Lawanson'],
    ['store-bernard-anari', 'Bernard anari', '22, lawanson road surulere', 'Surulere/Lawanson'],
    ['store-slot-onyinbo', 'Slot onyinbo', '71/73 murtala Mohammed way onyibo', 'Unilag'],
    ['store-micro-station-store', 'Micro station store', 'Shop 2, ogudu road off ikorodu way', 'Ikorodu'],
    ['store-ololo-mobile', 'Ololo Mobile', '7,nanka plaza opposite ajorin bus top', 'Surulere/Lawanson'],
    ['store-micro-station-mushin-2', 'Micro station mushin 2', '10, isolo road mushin', 'Oshodi/isolo'],
    ['store-chukwunonso-communication', 'Chukwunonso communication', '12, lawanson road off Gtb bank', 'Surulere/Lawanson'],
    ['store-de-dons-communications', "De Don's communications", '111/113 Agor palace way okota', 'Agor'],
    ['store-tele-hub', 'Tele hub', '7037605932', 'Agor'],
    ['store-icon-mobile-limited', 'Icon mobile limited', 'No 8 apapa road onyinbo beside 1st bank', 'Unilag'],
    ['store-me-and-u-connect-communication', 'Me and u connect communication', '36,murtala Muhammad way onyinbo bus stop beside uba bank', 'Unilag'],
    ['store-dreams-communications-gadgets', 'Dreams communications gadgets', 'Shop D16/D17 saka tinubu', 'Saka Tinubu'],
    ['store-jefas-stores', 'Jefas Stores', 'D12, 12 Saka Tinubu Street, GSM Plaza', 'Saka Tinubu'],
    ['store-good-will-communication', 'Good will communication', 'Shop D14 saka tinubu', 'Saka Tinubu'],
    ['store-kayla-yashim-venture', 'Kayla yashim venture', 'Shop 12 GSM Plaza saka tinubu', 'Saka Tinubu'],
    ['store-god-divine-venture', 'God divine venture', 'Shop E9 saka tinubu', 'Saka Tinubu'],
    ['store-tomasky-gadgets', 'Tomasky gadgets', '5,saka tinubu Victoria Island', 'Saka Tinubu'],
    ['store-adaugo-telecom', 'Adaugo telecom', 'Dyard lawanson', 'Surulere/Lawanson'],
    ['store-g-c-mor-communication', 'G.c mor communication', 'Shop B2c9 Alaba international market ojo', 'Alaba'],
    ['store-imotel-nigeria-limited', 'Imotel Nigeria limited', 'B270 olo alaba intentional', 'Alaba'],
    ['store-imotel-shop-2', 'Imotel shop 2', 'Shop b2 o7 Ojo alaba international market', 'Alaba'],
    ['store-cee-jame-communication', 'Cee jame communication', 'SHOp b121 Alaba international', 'Alaba'],
    ['store-rose', 'Rose', 'B160a Alaba international market', 'Alaba'],
    ['store-micro-station-saka-tinubu', 'Micro station saka tinubu', '12 ,saka tinubu Victoria Island', 'Saka Tinubu'],
    ['store-gosky-mobile', 'Gosky mobile', 'Destiny plaza agor', 'Agor'],
    ['store-glo-world', 'Glo world', '41,Adeniran ognsanya', 'Surulere/Lawanson'],
    ['store-tellus-communication', 'Tellus communication', '5,tele communication saka tinubu', 'Saka Tinubu'],
    ['store-folap-phone-shop', 'Folap phone shop', 'Shop E19 GSM plaza saka tinubu', 'Saka Tinubu'],
    ['store-nikky-p-phone-and-gadgets', 'Nikky p phone and gadgets', 'E16 gsm plaza saka tinubu', 'Saka Tinubu'],
    ['store-micro-station-saka-tinubu-2', 'Micro station saka. Tinubu 2', 'No.16 saka tinubu Victoria Island', 'Saka Tinubu'],
    ['store-ibn-international-concept', 'Ibn international concept', 'Shop A96 Abia plaza balogun trade fair lagos', 'Alaba'],
    ['store-golden-tech-view-communication-2', 'Golden tech view communication 2', 'SHOp 127, Exodus block trade fair', 'Alaba'],
    ['store-ada-communication', 'Ada communication', 'Shop 126, Exodus plaza trade faira', 'Alaba'],
    ['store-chidwc-communication-shop-2', 'Chidwc communication shop 2', '9137882127', 'Alaba'],
    ['store-sita-stevenson-ventures', 'Sita Stevenson Ventures', '31 old ojo road mama maza mile', 'Alaba'],
  ])),
  Ifeoma: allocation('Ifeoma', 'Chile Nwaiwu', ownedStores('Chile Nwaiwu', [
    ['store-kay-kay-beedhof-communication-venture-limitef', 'Kay Kay beedhof communication venture limitef', '23, lawanson road opposite total filling station', 'Surulere/Lawanson'],
    ['store-adintegra-phone-and-assesory', 'Adintegra phone and assesory', 'No 12 lawanson road surulere opposite Gtb bank', 'Surulere/Lawanson'],
    ['store-gods-design-communication', "God's design communication", 'No 130 itire road lawanson', 'Surulere/Lawanson'],
    ['store-j7-plus', 'J7 Plus', '130 itire rd , opposite bokku mart, lawanson surulere lagos', 'Surulere/Lawanson'],
    ['store-great-favour-multi-resources', 'Great favour multi resources', 'No 2 lawanson bus D yard plaza', 'Surulere/Lawanson'],
    ['store-chriskel-communications-ltd', 'Chriskel communications LTD', '130, lawanson road itire', 'Surulere/Lawanson'],
    ['store-fred-ime-communication', 'Fred ime communication', '130 lawanson road surulere', 'Surulere/Lawanson'],
    ['store-smig-technology-and-communications', 'Smig technology and communications', '135 , lawanson road off otun oba bus stop', 'Surulere/Lawanson'],
    ['store-go-sky-lawanson-ikenedu', 'Go sky lawanson ikenedu', 'Ikenedu business lawanson', 'Surulere/Lawanson'],
    ['store-wise-tech', 'Wise tech', 'Shop 2 ikedu building of Ashimowu bakare street off otun _obar', 'Surulere/Lawanson'],
    ['store-incredible-daniel-mobile', 'Incredible Daniel mobile', '12, lawanson road adjacent to Gtb bank', 'Surulere/Lawanson'],
    ['store-mobile-place-ng', 'Mobile place .Ng', 'Shop F24 d yard plaza lawanson village', 'Surulere/Lawanson'],
    ['store-lady-p', 'Lady p', '12, lawanson road opposite Gtb bank', 'Surulere/Lawanson'],
    ['store-3-chub-lawanson-2', '3 chub lawanson 2', '74 ojelegba road', 'Surulere/Lawanson'],
    ['store-rewjido-universal-service', 'Rewjido universal service', 'Tejuisho building beside mama tega', 'Surulere/Lawanson'],
    ['store-adaugo-telecoms-2', 'Adaugo Telecoms 2', 'Lawanson village the yard', 'Surulere/Lawanson'],
    ['store-pro-hub-mobile', 'Pro hub mobile', '130,//lawanson road opposite bokku', 'Surulere/Lawanson'],
    ['store-slot-lawanson', 'Slot lawanson', '43, lawanson road opposite zenith bqnk', 'Surulere/Lawanson'],
  ])),
  Peace: Object.freeze([]),
});

export function getAssignedStores(agentName) {
  return (STORE_ALLOCATIONS[agentName] || []).map((store) => store.name);
}

export function getAssignedStoreRecords(agentName) {
  return [...(STORE_ALLOCATIONS[agentName] || [])];
}

export function getAllAssignedStoreRecords() {
  return Object.values(STORE_ALLOCATIONS).flat();
}
